reporter: "xcode"

analyzer_rules:
  - unused_declaration
  - unused_import

disabled_rules:
  - conditional_returns_on_newline
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_self
  - explicit_top_level_acl
  - explicit_type_interface
  - force_unwrapping
  - indentation_width
  - implicit_return
  - nesting
  - object_literal
  - pattern_matching_keywords
  - switch_case_on_newline
  - todo
  - unowned_variable_capture
  - unused_capture_list
  - unused_optional_binding
  - unavailable_function

opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - collection_alignment
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - expiring_todo
  - extension_access_modifier
  - fatal_error_message
  - flatmap_over_map_reduce
  - file_header
  - file_name_no_space
  - first_where
  - function_default_parameter_at_end
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - logger_public
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - multiple_closures_with_trailing_closure
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prohibited_interface_builder
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - xct_specific_matcher
  - yoda_condition

file_header:
  required_pattern: \/\/ (swift-tools-version:\d.\d| Copyright © \d{4} Openpay\. All rights reserved\.)

trailing_comma:
  # Providing trailing commas on multi-line collection literals produces cleaner diffs
  mandatory_comma: true

indentation_width:
  indentation_width: 2

identifier_name:
  excluded: [id, x, y, z, r, g, b, a, i, j, k, cx, cy, dx, dy]

line_length:
  ignores_comments: true
  ignores_function_declarations: true
  warning: 180

type_name:
  allowed_symbols: _

custom_rules:
  print:
    name: "Use of print(), dump(), NSLog(), and debugPrint() is not allowed."
    message: "Use Logger API instead."
    match_kinds: [identifier]
    regex: "(print|dump|NSLog|debugPrint)\\("
    severity: warning
  logger_public:
    name: "Use of \"privacy: public\" in Logger strings is discouraged."
    regex: "privacy: \\.public"
    severity: warning
